export const ACTIONS = {
	SET_GROUP: 'SET_GROUP',
	SET_GROUP_MEMBERSHIP_ROLE: 'SET_GROUP_MEMBERSHIP_ROLE',
	SET_USERS: 'SET_USERS',
	TOGGLE_INVITE_MODAL: 'TOGGLE_INVITE_MODAL',

	SET_LOADING: 'SET_LOADING',

	SET_EVENTS: 'SET_EVENTS',
	TOGGLE_EVENT_RSVP: 'TOGGLE_EVENT_RSVP',
	CREATE_EVENT: 'CREATE_EVENT',
	RSVP: 'RSVP',
}
