export const ACTIONS = {
	SET_POSTS: 'SET_POSTS',
	SET_FOLLOWERS: 'SET_FOLLOWERS',
	SET_LOADING: 'SET_LOADING',
	SET_ERROR: 'SET_ERROR',
	SET_POST_PRIVACY: 'SET_POST_PRIVACY',
	ADD_COMMENT: 'ADD_COMMENT',
	CREATE_POST: 'CREATE_POST',
}
